/* SELÉNÉ — reálne produkty (katalóg rastie postupne, SKU = reálne) */
var CATS = {"nausnice": "Ohrringe", "nahrdelniky": "Halsketten", "prstene": "Ringe", "naramy": "Armbänder", "anklety": "Fußkettchen", "retiazky": "Ketten", "piercingy": "Piercingy"};
var COLLS = {"sun-gold": "Sun Gold", "moon-silver": "Moon Silver"};
var MATS = {"striebro": "Sterlingsilber 925", "ocel": "Chirurgischer Stahl", "pozlacene": "Pozlátené striebro"};
var PLATS = {"zlata": "Gold", "rodio": "Rhodiniert", "bez": "Ohne Beschichtung"};
var PRODUCTS = [
  {id:0, n:'Verstellbarer Ring mit Blume und rosa Zirkonen', t:'prstene', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:11.9, img:'../img/SEL-RI-9F4BA.jpg?v=2', sku:'SEL-RI-9F4BA', b:'novinka', gal:["../img/SEL-RI-9F4BA.jpg?v=2", "../img/SEL-RI-9F4BA_modelka_1.jpg?v=2", "../img/SEL-RI-9F4BA_modelka_2.jpg?v=2", "../img/SEL-RI-9F4BA_mockup.jpg?v=2"]},
  {id:1, n:'Fußkette 23 cm, doppelreihig mit Zirkonen', t:'anklety', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:17.95, img:'../img/SEL-AN-01242.jpg?v=2', sku:'SEL-AN-01242', b:'novinka', gal:["../img/SEL-AN-01242.jpg?v=2", "../img/SEL-AN-01242_modelka_1.jpg?v=2", "../img/SEL-AN-01242_mockup.jpg?v=2"]},
  {id:2, n:'Fußkette 23 cm, doppelreihig mit kleinen Zirkonen', t:'anklety', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:17.95, img:'../img/SEL-AN-71DE4.jpg?v=2', sku:'SEL-AN-71DE4', b:'novinka', gal:["../img/SEL-AN-71DE4.jpg?v=2", "../img/SEL-AN-71DE4_modelka_1.jpg?v=2", "../img/SEL-AN-71DE4_mockup.jpg?v=2"]},
  {id:3, n:'Goldenes Kleeblatt an Kette 43 cm', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:13.9, img:'../img/SEL-NE-BB21B.jpg?v=2', sku:'SEL-NE-BB21B', b:'novinka', gal:["../img/SEL-NE-BB21B.jpg?v=2", "../img/SEL-NE-BB21B_modelka_1.jpg?v=2", "../img/SEL-NE-BB21B_modelka_2.jpg?v=2", "../img/SEL-NE-BB21B_mockup.jpg?v=2"]},
  {id:4, n:'Armband 16 cm mit Steinen', t:'naramy', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:16.95, img:'../img/SEL-BR-673C2.jpg?v=2', sku:'SEL-BR-673C2', b:'novinka', gal:["../img/SEL-BR-673C2.jpg?v=2", "../img/SEL-BR-673C2_modelka_1.jpg?v=2", "../img/SEL-BR-673C2_modelka_2.jpg?v=2", "../img/SEL-BR-673C2_mockup.jpg?v=2"]},
  {id:5, n:'Ohrringe mit Blume 10 mm, hellrosa', t:'nausnice', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:8.9, img:'../img/SEL-EA-B8DCC.jpg?v=2', sku:'SEL-EA-B8DCC', b:'novinka', gal:["../img/SEL-EA-B8DCC.jpg?v=2", "../img/SEL-EA-B8DCC_modelka_1.jpg?v=2", "../img/SEL-EA-B8DCC_modelka_2.jpg?v=2", "../img/SEL-EA-B8DCC_mockup.jpg?v=2"]},
  {id:6, n:'Ohrringe 17 mm mit rechteckigen Zirkonen', t:'nausnice', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:14.9, img:'../img/SEL-EA-37240.jpg?v=2', sku:'SEL-EA-37240', b:'novinka', gal:["../img/SEL-EA-37240.jpg?v=2", "../img/SEL-EA-37240_modelka_1.jpg?v=2", "../img/SEL-EA-37240_modelka_2.jpg?v=2", "../img/SEL-EA-37240_mockup.jpg?v=2"]},
  {id:7, n:'Kette 40 cm mit Kreis aus Zirkonen', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:13.9, img:'../img/SEL-NE-1C80D.jpg?v=2', sku:'SEL-NE-1C80D', b:'novinka', gal:["../img/SEL-NE-1C80D.jpg?v=2", "../img/SEL-NE-1C80D_modelka_1.jpg?v=2", "../img/SEL-NE-1C80D_modelka_2.jpg?v=2", "../img/SEL-NE-1C80D_mockup.jpg?v=2"]},
  {id:8, n:'Ring mit kleinen Perlen 2 mm', t:'prstene', m:'ocel', pl:'zlata', s:'perla', k:'sun-gold', c:9.9, img:'../img/SEL-RI-14337.jpg?v=2', sku:'SEL-RI-14337', b:'novinka', gal:["../img/SEL-RI-14337.jpg?v=2", "../img/SEL-RI-14337_modelka_1.jpg?v=2", "../img/SEL-RI-14337_modelka_2.jpg?v=2", "../img/SEL-RI-14337_mockup.jpg?v=2"]},
  {id:9, n:'Armband 17 cm mit Blume und Zirkonen', t:'naramy', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:11.9, img:'../img/SEL-BR-9DBC9.jpg?v=2', sku:'SEL-BR-9DBC9', b:'novinka', gal:["../img/SEL-BR-9DBC9.jpg?v=2", "../img/SEL-BR-9DBC9_modelka_1.jpg?v=2", "../img/SEL-BR-9DBC9_modelka_2.jpg?v=2", "../img/SEL-BR-9DBC9_mockup.jpg?v=2"]},
  {id:10, n:'Kette 40 cm mit zwei Blumen aus Zirkonen', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:14.9, img:'../img/SEL-NE-C6B45.jpg?v=2', sku:'SEL-NE-C6B45', b:'novinka', gal:["../img/SEL-NE-C6B45.jpg?v=2", "../img/SEL-NE-C6B45_modelka_1.jpg?v=2", "../img/SEL-NE-C6B45_modelka_2.jpg?v=2", "../img/SEL-NE-C6B45_mockup.jpg?v=2"]},
];
