/* SELÉNÉ — reálne produkty (katalóg rastie postupne, SKU = reálne) */
var CATS = {"nausnice": "Náušnice", "nahrdelniky": "Náhrdelníky", "prstene": "Prstene", "naramy": "Náramky", "anklety": "Retiazky na nohu", "retiazky": "Retiazky", "piercingy": "Piercingy"};
var COLLS = {"sun-gold": "Sun Gold", "moon-silver": "Moon Silver"};
var MATS = {"striebro": "Striebro 925", "ocel": "Chirurgická oceľ", "pozlacene": "Pozlátené striebro"};
var PLATS = {"zlata": "Zlatá", "rodio": "Ródiovaná", "bez": "Bez pokovenia"};
var PRODUCTS = [
  {id:0, n:'Nastaviteľný prsteň s kvetom a ružovými zirkónmi', t:'prstene', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:11.9, img:'img/SEL-RI-9F4BA.jpg', sku:'SEL-RI-9F4BA', b:'novinka', gal:["img/SEL-RI-9F4BA.jpg", "img/SEL-RI-9F4BA_detail.jpg", "img/SEL-RI-9F4BA_modelka_2.jpg", "img/SEL-RI-9F4BA_modelka_1.jpg", "img/SEL-RI-9F4BA_mockup.jpg"]},
  {id:1, n:'Retiazka na nohu 23 cm, dvojradová so zirkónmi', t:'anklety', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:17.95, img:'img/SEL-AN-01242.jpg', sku:'SEL-AN-01242', b:'novinka', gal:["img/SEL-AN-01242.jpg", "img/SEL-AN-01242_detail.jpg", "img/SEL-AN-01242_modelka_2.jpg", "img/SEL-AN-01242_modelka_1.jpg", "img/SEL-AN-01242_mockup.jpg"]},
  {id:2, n:'Retiazka na nohu 23 cm, dvojradová s drobnými zirkónmi', t:'anklety', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:17.95, img:'img/SEL-AN-71DE4.jpg', sku:'SEL-AN-71DE4', b:'novinka', gal:["img/SEL-AN-71DE4.jpg", "img/SEL-AN-71DE4_detail.jpg", "img/SEL-AN-71DE4_modelka_2.jpg", "img/SEL-AN-71DE4_modelka_1.jpg", "img/SEL-AN-71DE4_mockup.jpg"]},
  {id:3, n:'Zlatý štvorlístok na retiazke 43 cm', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:13.9, img:'img/SEL-NE-BB21B.jpg', sku:'SEL-NE-BB21B', b:'novinka', gal:["img/SEL-NE-BB21B.jpg", "img/SEL-NE-BB21B_detail.jpg", "img/SEL-NE-BB21B_modelka_2.jpg", "img/SEL-NE-BB21B_modelka_1.jpg", "img/SEL-NE-BB21B_mockup.jpg"]},
  {id:4, n:'Náramok 16 cm s kamienkami', t:'naramy', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:16.95, img:'img/SEL-BR-673C2.jpg', sku:'SEL-BR-673C2', b:'novinka', gal:["img/SEL-BR-673C2.jpg", "img/SEL-BR-673C2_detail.jpg", "img/SEL-BR-673C2_modelka_2.jpg", "img/SEL-BR-673C2_modelka_1.jpg", "img/SEL-BR-673C2_mockup.jpg"]},
  {id:5, n:'Náušnice s kvetom 10 mm, svetloružové', t:'nausnice', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:8.9, img:'img/SEL-EA-B8DCC.jpg', sku:'SEL-EA-B8DCC', b:'novinka', gal:["img/SEL-EA-B8DCC.jpg", "img/SEL-EA-B8DCC_detail.jpg", "img/SEL-EA-B8DCC_modelka_2.jpg", "img/SEL-EA-B8DCC_modelka_1.jpg", "img/SEL-EA-B8DCC_mockup.jpg"]},
];
