/* SELÉNÉ — reálne produkty (72) z katalógu */
var CATS = {"nausnice": "Náušnice", "nahrdelniky": "Náhrdelníky", "prstene": "Prstene", "naramy": "Náramky", "anklety": "Retiazky na nohu", "retiazky": "Retiazky"};
var COLLS = {"sun-gold": "Sun Gold", "moon-silver": "Moon Silver"};
var MATS = {"striebro": "Striebro 925", "ocel": "Chirurgická oceľ", "pozlacene": "Pozlátené striebro"};
var PLATS = {"zlata": "Zlatá", "rodio": "Ródiovaná", "bez": "Bez pokovenia"};
var PRODUCTS = [
  {id:0, n:'Mušľové náušnice s perlou', t:'nausnice', m:'striebro', pl:'zlata', s:'perla', k:'sun-gold', c:39, img:'img/nagosa_ear_0.jpg', b:'bestseller'},
  {id:1, n:'Huggie kruhy s zirkónmi', t:'nausnice', m:'striebro', pl:'zlata', s:'zirkon', k:'sun-gold', c:35, img:'img/nagosa_ear_1.jpg'},
  {id:2, n:'Dvojité huggie kruhy 925', t:'nausnice', m:'striebro', pl:'rodio', s:'bez', k:'moon-silver', c:35, img:'img/nagosa_ear_2.jpg'},
  {id:3, n:'Perlové mušľové náušnice', t:'nausnice', m:'striebro', pl:'zlata', s:'perla', k:'sun-gold', c:39, img:'img/nagosa_neck_0.jpg', b:'novinka'},
  {id:4, n:'Krúžky s zirkónmi 13 mm', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:19, img:'img/dottilove/hoops_3.jpg'},
  {id:5, n:'Kruhy s zirkónmi 18 mm', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:21, img:'img/dottilove/hoops_5.jpg'},
  {id:6, n:'Vlnité kruhy s zirkónmi', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:21, img:'img/dottilove/hoops_7.jpg'},
  {id:7, n:'Zlaté nepravidelné kruhy', t:'nausnice', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:23, img:'img/dottilove/hoops_8.jpg', b:'novinka'},
  {id:8, n:'Pozlátené kruhy CZ 16 mm', t:'nausnice', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:25, img:'img/dottilove/hoops_9.jpg', b:'bestseller'},
  {id:9, n:'Pozlátené kruhy s farb. zirkónmi', t:'nausnice', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:27, img:'img/dottilove/hoops_11.jpg'},
  {id:10, n:'Obdĺžnikové krúžky 17 mm', t:'nausnice', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:19, img:'img/dottilove/hoops_12.jpg'},
  {id:11, n:'Esíčkové krúžky 17 mm', t:'nausnice', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:19, img:'img/dottilove/hoops_13.jpg'},
  {id:12, n:'Vintage krúžky CZ 28 mm', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:24, img:'img/dottilove/earrings_3.jpg'},
  {id:13, n:'Osmičkové náušnice CZ', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:22, img:'img/dottilove/earrings_6.jpg'},
  {id:14, n:'Štvorlístkové náušnice CZ', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:22, img:'img/dottilove/earrings_9.jpg'},
  {id:15, n:'C-krúžky s zirkónmi 13 mm', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:20, img:'img/dottilove/earrings_10.jpg'},
  {id:16, n:'Náušnice s 4 zirkónmi', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:23, img:'img/dottilove/earrings_11.jpg'},
  {id:17, n:'Lancetové náušnice s zirkónmi', t:'nausnice', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:23, img:'img/dottilove/earrings_13.jpg'},
  {id:18, n:'Čerešničkové napichovacie náušnice', t:'nausnice', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:25, img:'img/faire/rosies_0.jpg', b:'bestseller'},
  {id:19, n:'Ružové motýlikové náušnice', t:'nausnice', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:25, img:'img/faire/rosies_1.jpg'},
  {id:20, n:'Kvetinové náušnice', t:'nausnice', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:27, img:'img/faire/rosies_2.jpg'},
  {id:21, n:'Žiariace ružové kvety', t:'nausnice', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:27, img:'img/faire/rosies_4.jpg', b:'novinka'},
  {id:22, n:'Broskyňové mesačné náušnice s perlou', t:'nausnice', m:'ocel', pl:'bez', s:'perla', k:'moon-silver', c:32, img:'img/faire/rosies_12.jpg', b:'bestseller'},
  {id:23, n:'Zlatá mašlička s perlou', t:'nahrdelniky', m:'striebro', pl:'zlata', s:'perla', k:'sun-gold', c:49, img:'img/nagosa_neck_3.jpg', b:'bestseller'},
  {id:24, n:'Strieborná perla na retiazke', t:'nahrdelniky', m:'striebro', pl:'rodio', s:'perla', k:'moon-silver', c:45, img:'img/nagosa_neck_5.jpg'},
  {id:25, n:'Zlatý štvorlístok', t:'nahrdelniky', m:'striebro', pl:'zlata', s:'bez', k:'sun-gold', c:45, img:'img/nagosa_neck_1.jpg'},
  {id:26, n:'Dvojitý náhrdelník', t:'nahrdelniky', m:'striebro', pl:'zlata', s:'bez', k:'sun-gold', c:55, img:'img/nagosa_neck_2.jpg', b:'novinka'},
  {id:27, n:'Retiazka s filigránovým zirkónom', t:'nahrdelniky', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:29, img:'img/dottilove/necklaces_3.jpg'},
  {id:28, n:'Náhrdelník so zlatým diskom 40 cm', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:31, img:'img/dottilove/necklaces_6.jpg', b:'bestseller'},
  {id:29, n:'Náhrdelník s otvoreným srdcom 95 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:33, img:'img/dottilove/necklaces_7.jpg'},
  {id:30, n:'Ploché srdce na retiazke 100 cm', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:33, img:'img/dottilove/necklaces_8.jpg'},
  {id:31, n:'Náhrdelník so štvorlístkom 80 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:31, img:'img/dottilove/necklaces_9.jpg'},
  {id:32, n:'Retiazka s detailom 80 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:35, img:'img/dottilove/necklaces_10.jpg', b:'novinka'},
  {id:33, n:'Štvorcový prívesok 42 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:27, img:'img/dottilove/necklaces_11.jpg'},
  {id:34, n:'Náhrdelník s trojlístkom 43 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:27, img:'img/dottilove/necklaces_12.jpg'},
  {id:35, n:'Drobný trojlístok 39 cm', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:26, img:'img/dottilove/necklaces_13.jpg'},
  {id:36, n:'Opal Sun Moon prívesok 925', t:'nahrdelniky', m:'striebro', pl:'rodio', s:'opal', k:'moon-silver', c:59, img:'img/faire/perimade_1.jpg', b:'bestseller'},
  {id:37, n:'Ružový kremeň Tulip 925', t:'nahrdelniky', m:'striebro', pl:'rodio', s:'kremen', k:'moon-silver', c:55, img:'img/faire/perimade_2.jpg'},
  {id:38, n:'Opal Sun Moon dvojretiazka 925', t:'nahrdelniky', m:'striebro', pl:'rodio', s:'opal', k:'moon-silver', c:65, img:'img/faire/perimade_3.jpg', b:'novinka'},
  {id:39, n:'Krištáľová kvapka', t:'nahrdelniky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:29, img:'img/faire/rosies_6.jpg'},
  {id:40, n:'Baroková perla Rosy 18k', t:'nahrdelniky', m:'ocel', pl:'zlata', s:'perla', k:'sun-gold', c:49, img:'img/faire/rosies_11.jpg', b:'bestseller'},
  {id:41, n:'Voľný prsteň', t:'prstene', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:19, img:'img/dottilove/rings_0.jpg'},
  {id:42, n:'Mini bodkovaný prsteň', t:'prstene', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:19, img:'img/dottilove/rings_1.jpg'},
  {id:43, n:'Prsteň s dvojitým zirkónom', t:'prstene', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:23, img:'img/dottilove/rings_2.jpg', b:'bestseller'},
  {id:44, n:'Dvojitý zirkónový prsteň', t:'prstene', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:24, img:'img/dottilove/rings_3.jpg'},
  {id:45, n:'Dvojitý prsteň s CZ', t:'prstene', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:24, img:'img/dottilove/rings_4.jpg'},
  {id:46, n:'Výrazný prsteň s zirkónmi', t:'prstene', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:27, img:'img/dottilove/rings_5.jpg', b:'novinka'},
  {id:47, n:'Prsteň s pásom CZ', t:'prstene', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:23, img:'img/dottilove/rings_6.jpg'},
  {id:48, n:'Prsteň s drobnými zirkónmi', t:'prstene', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:21, img:'img/dottilove/rings_7.jpg'},
  {id:49, n:'Zlatý krúžok', t:'prstene', m:'striebro', pl:'zlata', s:'bez', k:'sun-gold', c:29, img:'img/nagosa_neck_7.jpg'},
  {id:50, n:'Kvetinový prsteň Dreamy', t:'prstene', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:25, img:'img/faire/rosies_7.jpg', b:'novinka'},
  {id:51, n:'Prsteň Rosie', t:'prstene', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:23, img:'img/faire/rosies_9.jpg'},
  {id:52, n:'Prsteň s kameňom', t:'prstene', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:25, img:'img/faire/rosies_10.jpg'},
  {id:53, n:'Náramok s dvoma CZ', t:'naramy', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:27, img:'img/dottilove/bracelets_3.jpg'},
  {id:54, n:'Náramok s dvojitým krúžkom', t:'naramy', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:29, img:'img/dottilove/bracelets_6.jpg'},
  {id:55, n:'Náramok twin-ring', t:'naramy', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:29, img:'img/dottilove/bracelets_7.jpg'},
  {id:56, n:'Dvojradový náramok', t:'naramy', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:31, img:'img/dottilove/bracelets_8.jpg', b:'novinka'},
  {id:57, n:'Retiazkový náramok 17 cm', t:'naramy', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:27, img:'img/dottilove/bracelets_9.jpg'},
  {id:58, n:'Náramok plný trblietok', t:'naramy', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:29, img:'img/dottilove/bracelets_10.jpg'},
  {id:59, n:'Náramok s zirkónmi', t:'naramy', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:29, img:'img/dottilove/bracelets_11.jpg'},
  {id:60, n:'Náramok s 5 srdiečkami', t:'naramy', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:30, img:'img/dottilove/bracelets_12.jpg', b:'bestseller'},
  {id:61, n:'Náramok s CZ', t:'naramy', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:28, img:'img/dottilove/bracelets_13.jpg'},
  {id:62, n:'Pozlátený náramok s kameňmi', t:'naramy', m:'ocel', pl:'zlata', s:'zirkon', k:'sun-gold', c:35, img:'img/faire/rosies_13.jpg', b:'novinka'},
  {id:63, n:'Retiazka na nohu s morskými motívmi', t:'anklety', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:21, img:'img/dottilove/anklets_3.jpg'},
  {id:64, n:'Retiazka na nohu mini CZ', t:'anklety', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:19, img:'img/dottilove/anklets_6.jpg'},
  {id:65, n:'Retiazka na nohu so 6 zirkónmi', t:'anklety', m:'ocel', pl:'bez', s:'zirkon', k:'moon-silver', c:21, img:'img/dottilove/anklets_7.jpg'},
  {id:66, n:'Retiazka na nohu s perlou', t:'anklety', m:'ocel', pl:'zlata', s:'perla', k:'sun-gold', c:23, img:'img/dottilove/anklets_8.jpg', b:'bestseller'},
  {id:67, n:'Dvojitá retiazka na nohu', t:'anklety', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:22, img:'img/dottilove/anklets_9.jpg'},
  {id:68, n:'Retiazka na nohu s kosoštvorcami', t:'anklety', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:21, img:'img/dottilove/anklets_11.jpg'},
  {id:69, n:'Retiazka na nohu double chain', t:'anklety', m:'ocel', pl:'zlata', s:'bez', k:'sun-gold', c:22, img:'img/dottilove/anklets_12.jpg'},
  {id:70, n:'Retiazka na nohu s bead chain', t:'anklety', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:22, img:'img/dottilove/anklets_13.jpg'},
  {id:71, n:'Retiazka Noa', t:'retiazky', m:'ocel', pl:'bez', s:'bez', k:'moon-silver', c:29, img:'img/faire/rosies_5.jpg', b:'novinka'},
];